"""Added contest related table

Revision ID: 26ba94b8e796
Revises: dc15c595d08
Create Date: 2015-06-02 11:03:13.383342

"""

# revision identifiers, used by Alembic.
revision = '26ba94b8e796'
down_revision = 'dc15c595d08'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('problems',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contest_id', sa.Integer(), nullable=True),
    sa.Column('name_vi', sa.String(length=255), nullable=True),
    sa.Column('name_en', sa.String(length=255), nullable=True),
    sa.Column('content_vi', sa.Text(), nullable=True),
    sa.Column('content_en', sa.Text(), nullable=True),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('limited_time', sa.Integer(), nullable=True),
    sa.Column('limited_memory', sa.Integer(), nullable=True),
    sa.Column('limited_source_size', sa.Integer(), nullable=True),
    sa.Column('starting_point', sa.Integer(), nullable=True),
    sa.Column('wrong_answer_decreased_point', sa.Integer(), nullable=True),
    sa.Column('slowly_decreased_interval', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['contest_id'], ['contests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('contest_id', sa.Integer(), nullable=True),
    sa.Column('point', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['contest_id'], ['contests.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('submissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('problem_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('language', sa.Integer(), nullable=True),
    sa.Column('state', sa.String(length=255), nullable=True),
    sa.Column('result_status', sa.String(length=255), nullable=True),
    sa.Column('last_passed_test_case', sa.Integer(), nullable=True),
    sa.Column('used_time', sa.Integer(), nullable=True),
    sa.Column('used_memory', sa.Integer(), nullable=True),
    sa.Column('received_point', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('failed_test_case_result', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['problem_id'], ['problems.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('submissions')
    op.drop_table('user_scores')
    op.drop_table('problems')
    ### end Alembic commands ###
