"""Add student_id for user

Revision ID: 26e33690d5a2
Revises: 37fde361d122
Create Date: 2016-01-12 14:23:23.460405

"""

# revision identifiers, used by Alembic.
revision = '26e33690d5a2'
down_revision = '37fde361d122'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
