"""Add category for problem

Revision ID: 2d73b23556cf
Revises: 26e33690d5a2
Create Date: 2016-01-12 15:10:47.811934

"""

# revision identifiers, used by Alembic.
revision = '2d73b23556cf'
down_revision = '26e33690d5a2'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('problems', sa.Column('category', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('problems', 'category')
    ### end Alembic commands ###
