"""Add user forgot password table

Revision ID: 4b58f025d0a
Revises: 26ba94b8e796
Create Date: 2015-07-16 13:16:13.164040

"""

# revision identifiers, used by Alembic.
revision = '4b58f025d0a'
down_revision = '26ba94b8e796'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_forgot_passwords',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=40), nullable=True),
    sa.Column('expire_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.drop_index('index_problems_on_contest_id', table_name='problems')
    op.create_foreign_key(None, 'problems', 'contests', ['contest_id'], ['id'])
    op.drop_index('index_submissions_on_problem_id', table_name='submissions')
    op.drop_index('index_submissions_on_user_id', table_name='submissions')
    op.create_foreign_key(None, 'submissions', 'problems', ['problem_id'], ['id'])
    op.create_foreign_key(None, 'submissions', 'users', ['user_id'], ['id'])
    op.drop_index('index_user_scores_on_contest_id', table_name='user_scores')
    op.drop_index('index_user_scores_on_user_id', table_name='user_scores')
    op.create_foreign_key(None, 'user_scores', 'contests', ['contest_id'], ['id'])
    op.create_foreign_key(None, 'user_scores', 'users', ['user_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_scores', type_='foreignkey')
    op.drop_constraint(None, 'user_scores', type_='foreignkey')
    op.create_index('index_user_scores_on_user_id', 'user_scores', ['user_id'], unique=False)
    op.create_index('index_user_scores_on_contest_id', 'user_scores', ['contest_id'], unique=False)
    op.drop_constraint(None, 'submissions', type_='foreignkey')
    op.drop_constraint(None, 'submissions', type_='foreignkey')
    op.create_index('index_submissions_on_user_id', 'submissions', ['user_id'], unique=False)
    op.create_index('index_submissions_on_problem_id', 'submissions', ['problem_id'], unique=False)
    op.drop_constraint(None, 'problems', type_='foreignkey')
    op.create_index('index_problems_on_contest_id', 'problems', ['contest_id'], unique=False)
    op.drop_table('user_forgot_passwords')
    ### end Alembic commands ###
